adjective1 = input("Enter adjective1:")
noun =  input("Enter noun:")
adjective2 =  input("Enter adjective2:")
verb =  input("Enter verb:")
adjective3 =  input("Enter adjective3:")

print(f'today i went to a {adjective1 } zoo')
print(f"In an exhibit, I swa {noun}")
print(f"{noun} was {adjective2} and {verb}ing")
print(f"I was {adjective3}")